In [1]:
with open('SMSSpamCollection.txt','r') as file:
    data = file.read()

In [2]:
# len(data)  # total emails 

In [3]:
# data.split('\n')
# [line1, line2, line3, line n] 
# data[1]

In [4]:
email_ls = data.split('\n')
# email_ls

In [5]:
# x = []
# y = []
# label_email = email_ls[1].split('\t')
# x.append(label_email[1])
# y.append(label_email[0])

In [6]:
x = [] 
y = [] 
for line in email_ls:
    email_with_labels = line.split('\t')
    if len(email_with_labels) == 2:
        x.append(email_with_labels[1])
        y.append(email_with_labels[0])

In [7]:
len(x) , len(y)

(5574, 5574)

In [8]:
x[10]

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [9]:
y[10]

'ham'

In [10]:
# Model trainer 
import re  

In [11]:
x[21]

'I‘m going to try for 2 months ha ha only joking'

In [12]:
ls = "Hii i am from @gayaand pincode 823001"
re.sub('[^a-zA-Z ]','',x[21]).lower()

'im going to try for  months ha ha only joking'

In [13]:
for i in range(len(x)):
    x[i] = re.sub('[^a-zA-Z ]','',x[i]).lower()

In [14]:
x[21]

'im going to try for  months ha ha only joking'

In [15]:
import pandas as pd 
dt = {"email_message":x,"label":y}
df = pd.DataFrame(dt) 
df.head()

email_message label
0  go until jurong point crazy available only in ...   ham
1                            ok lar joking wif u oni   ham
2  free entry in  a wkly comp to win fa cup final...  spam
3        u dun say so early hor u c already then say   ham
4  nah i dont think he goes to usf he lives aroun...   ham

In [16]:
df['label'].value_counts()
#  spam other data add 
# ham data points remove 

label
ham     4827
spam     747
Name: count, dtype: int64

In [17]:
ham = df[df['label']=='ham']
spam = df[df['label']=='spam']

In [18]:
ham.shape   ,    spam.shape 

((4827, 2), (747, 2))

In [19]:
ham.sample(1000).shape 

(1000, 2)

In [20]:
ham = ham.sample(1000) 

In [21]:
ham.shape, spam.shape

((1000, 2), (747, 2))

In [22]:
balance_df = pd.concat([ham,spam])

In [23]:
balance_df['label'].value_counts()

label
ham     1000
spam     747
Name: count, dtype: int64

In [24]:
x = balance_df['email_message']
y = balance_df['label']

In [25]:
x = x.values
type(x)

numpy.ndarray

In [26]:
### email message transform into numerical 

from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
bow =  CountVectorizer(max_features=1700,stop_words='english',)
# bag of words 

In [27]:
x = bow.fit_transform(x).toarray()

In [28]:
x.shape

(1747, 1700)

In [29]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
column_name = bow.get_feature_names_out()  # unique 
column_name

array(['able', 'abt', 'abta', ..., 'yrs', 'yup', 'zed'], dtype=object)

In [31]:
testing =pd.DataFrame(x,columns=column_name)

In [32]:
# pd.set_option('display.max_rows',None)
# pd.set_option('display.max_rows',None)

In [33]:
testing

able  abt  abta  ac  access  account  action  activate  actually  \
0        0    0     0   0       0        0       0         0         0   
1        0    0     0   0       0        0       0         0         0   
2        0    0     0   0       0        0       0         0         0   
3        0    0     0   0       0        0       0         0         0   
4        0    0     0   0       0        0       0         0         0   
...    ...  ...   ...  ..     ...      ...     ...       ...       ...   
1742     0    0     0   0       0        0       0         0         0   
1743     0    0     0   0       0        0       0         0         0   
1744     0    0     0   0       0        0       0         0         0   
1745     0    0     0   0       0        0       0         0         0   
1746     0    0     0   0       0        0       0         0         0   

      address  ...  yes  yesterday  yo  youll  youre  youve  yr  yrs  yup  zed  
0           0  ...    0          0   0      0      0      0   0    0    0    0  
1           0  ...    0          0   0      0      0      0   0    0    0    0  
2           0  ...    0          0   0      0      0      0   0    0    0    0  
3           0  ...    0          0   0      0      0      0   0    0    0    0  
4           0  ...    0          0   0      0      0      0   0    0    0    0  
...       ...  ...  ...        ...  ..    ...    ...    ...  ..  ...  ...  ...  
1742        0  ...    0          0   0      0      0      0   0    0    0    0  
1743        0  ...    1          0   0      0      0      0   0    0    0    0  
1744        0  ...    1          0   0      0      0      0   0    0    0    0  
1745        0  ...    0          0   0      0      0      0   0    0    0    0  
1746        0  ...    0          0   0      0      0      0   0    0    0    0  

[1747 rows x 1700 columns]

In [34]:
# ham = 0  
# spam = 1  
dt = {'ham':0,'spam':1}
y = y.map(dt)

In [35]:
import numpy as np 

In [36]:
y = np.array(y)

In [37]:
x.shape , y.shape 

((1747, 1700), (1747,))

In [38]:
# train test split 
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15)

In [40]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB 

In [41]:
# Logisticregression
# decisiontree classifier 
# randomforest classifier

In [42]:
# Logisticregression
# decisiontree classifier 
# randomforest classifier   
mb = MultinomialNB()
bnb = BernoulliNB() 

mb.fit(x_train,y_train) 
bnb.fit(x_train,y_train) 

print("Training score MNB : ",mb.score(x_train,y_train)*100)
print("Testing score MNB : ",mb.score(x_test,y_test)*100)
print()
print("Training score bnb : ",bnb.score(x_train,y_train)*100)
print("Testing score bnb : ",bnb.score(x_test,y_test)*100)

Training score MNB :  97.50673854447439
Testing score MNB :  95.43726235741445

Training score bnb :  95.95687331536388
Testing score bnb :  96.57794676806084


In [43]:
import joblib 

In [44]:
joblib.dump(bnb,'BNB_Model.lb')
joblib.dump(bow,'countvectorizer.lb')

['countvectorizer.lb']

In [45]:
# prediction 

In [46]:
prediction = bnb.predict(x_test)

In [47]:
prediction[:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [48]:
y_test[:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [49]:
from sklearn.metrics import confusion_matrix

In [50]:
confusion_matrix(y_test,prediction)

array([[161,   0],
       [  9,  93]], dtype=int64)