In [20]:
import numpy as np

In [21]:
a = np.random.randint(1,30,(5,6))
a

array([[17, 21, 29, 13, 28, 20],
       [26,  3, 12,  6,  2,  8],
       [24, 18, 17,  9, 12, 20],
       [12, 17, 17, 23, 11, 11],
       [25,  6, 10, 22,  7, 15]])

In [22]:
bool_Arr = a>20
print(bool_Arr)

[[False  True  True False  True False]
 [ True False False False False False]
 [ True False False False False False]
 [False False False  True False False]
 [ True False False  True False False]]


In [23]:
arr = a[bool_Arr]
print(arr)

[21 29 28 26 24 23 25 22]


In [24]:
b = a
print(a)

[[17 21 29 13 28 20]
 [26  3 12  6  2  8]
 [24 18 17  9 12 20]
 [12 17 17 23 11 11]
 [25  6 10 22  7 15]]


In [25]:
b[bool_Arr]==100
print(b)

[[17 21 29 13 28 20]
 [26  3 12  6  2  8]
 [24 18 17  9 12 20]
 [12 17 17 23 11 11]
 [25  6 10 22  7 15]]


In [26]:
c = np.random.randint(1,10,(2,2))
print(c)

[[5 5]
 [9 2]]


In [27]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [28]:
# print(c[c_bool])

In [29]:
print(b)

[[17 21 29 13 28 20]
 [26  3 12  6  2  8]
 [24 18 17  9 12 20]
 [12 17 17 23 11 11]
 [25  6 10 22  7 15]]


In [33]:
bool_Arr = b[:,3] == 23
print(bool_Arr)


[False False False  True False]


In [34]:
b[bool_Arr,3] = 99
print(b)

[[17 21 29 13 28 20]
 [26  3 12  6  2  8]
 [24 18 17  9 12 20]
 [12 17 17 99 11 11]
 [25  6 10 22  7 15]]
