In [1]:
import numpy as np

In [2]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

In [3]:
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[19 17 12  2  3]
[9 5 9 4 2]


In [4]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [5]:
a = a+1
a

array([20, 18, 13,  3,  4])

In [6]:
c = a+b
c

array([29, 23, 22,  7,  6])

In [7]:
d = c-b
d

array([20, 18, 13,  3,  4])

In [8]:
e = a*b
e

array([180,  90, 117,  12,   8])

In [9]:
f = a/b
f

array([2.22222222, 3.6       , 1.44444444, 0.75      , 2.        ])

In [10]:
g = a**b
g

array([ 898891776,    1889568, 2014564781,         81,         16])

In [11]:
h = a//b
h

array([2, 3, 1, 0, 2])

In [12]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmax())
print(a.argmin())

58
11.6
3
0
3


In [13]:
a>b

array([ True,  True,  True, False,  True])

In [14]:
a<b

array([False, False, False,  True, False])

In [15]:
a==b

array([False, False, False, False, False])

In [16]:
a!=b

array([ True,  True,  True,  True,  True])

In [17]:
a>=b

array([ True,  True,  True, False,  True])

In [18]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [19]:
print(np.logical_not(a,b))

[0 0 0 0 0]
