In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,10,(3,3))

In [3]:
y = np.random.randint(1,10,(3,3))

In [4]:
print(x)
print(y)

[[9 4 5]
 [9 6 6]
 [7 6 1]]
[[3 2 6]
 [5 2 3]
 [8 5 5]]


In [5]:
x+y

array([[12,  6, 11],
       [14,  8,  9],
       [15, 11,  6]])

In [6]:
x*y

array([[27,  8, 30],
       [45, 12, 18],
       [56, 30,  5]])

In [7]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[4 1 3]
 [4 4 5]
 [7 3 8]]
[1 3 3]


In [8]:
x-y

array([[ 3, -2,  0],
       [ 3,  1,  2],
       [ 6,  0,  5]])

In [9]:
x = np.random.randint(1,10,(2,3))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[1 3 4]
 [5 4 2]]
[[3 8]
 [6 8]
 [1 4]]


In [11]:
# x-y

In [12]:
y = np.transpose(y)
y

array([[3, 6, 1],
       [8, 8, 4]])

In [13]:
x-y

array([[-2, -3,  3],
       [-3, -4, -2]])