In [19]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [20]:
print(li[3])
print(li[1:4])
print(li[4])
print(arr[3])

4
[2, 3, 4]
5
4


In [21]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [22]:
lid_2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(lid_2)
print(lid_2)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [24]:
print(lid_2[2][2])
print(arr_2d[2][2])

11
11


In [25]:
print(lid_2[1][0:4])
print(arr_2d[1][0:4])

[5, 6, 7, 8]
[5 6 7 8]


In [26]:
x = lid_2[0:3]
print(x)
y = x[2]
y

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


[9, 10, 11, 12]

In [27]:
lid_3 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_3d = np.array(lid_3)
print(lid_3)
print(arr_3d)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
print(arr_3d[2,0:3])
print(arr_3d[1:4,3])
print(arr_3d[2:4][0:4])
print(arr_3d[1:4,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]
 [17 18]]
