In [1]:
import numpy as np

In [2]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[15 15 13 12  7  2  1  7]


In [3]:
print(b>10)

[ True  True  True  True False False False False]


In [4]:
bool_Arr = b>10
print(bool_Arr)
new_Arr = b[bool_Arr]
print(new_Arr)

[ True  True  True  True False False False False]
[15 15 13 12]


In [5]:
new_Arr = b[(b>10) & (b<15)]
new_Arr

array([13, 12])

In [6]:
print(b)

[15 15 13 12  7  2  1  7]


In [7]:
new_Arr = b[(b>10)&(b<19)]
new_Arr

array([15, 15, 13, 12])

In [8]:
c=b

In [9]:
print(c)

[15 15 13 12  7  2  1  7]


In [10]:
c[c>12] = 100
c

array([100, 100, 100,  12,   7,   2,   1,   7])

In [11]:
print(b)

[100 100 100  12   7   2   1   7]


In [12]:
print(b[b==100])

[100 100 100]


In [13]:
inx = np.where(b==100)
inx

(array([0, 1, 2], dtype=int64),)

In [16]:
Array = np.array([1,2,0,0,4,0])
idx = np.where(Array==0)
idx

(array([2, 3, 5], dtype=int64),)

In [17]:
Array_1 = np.array([1,3,5,7,9,11,13,15,17,19])
idx_1 = np.where(Array_1%3==0)
idx_1

(array([1, 4, 7], dtype=int64),)

In [20]:
Array_2 = np.array([1,2,3,4,5,6,7,8,9,10])
Array_2[Array_2%2!=0] = -1
print(Array_2)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [27]:
Array_3 = np.array([11,2,13,4,15,6,27,8,19])
max_value = Array_3.max()
Array_3[Array_3==max_value] = 0
print(Array_3)

[11  2 13  4 15  6  0  8 19]


In [29]:
Array_4 = np.array([1,2,3,4,5,6,7,8,9,10])
Array_4[(Array_4>=3) & (Array_4<=8)] = -1
print(Array_4)

[ 1  2 -1 -1 -1 -1 -1 -1  9 10]


In [ ]:
Age = np.array([40,43,60,22,32,12,23,12,67,76])
height = np.array([120,124,132,110,114,190,167,130,180,160])
Age_Height = np.array([()])