In [1]:
import numpy as np

In [3]:
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
a = [1,2,3,5,8,2.0]
b = np.array(a,dtype=int)
print(b) 
#numpy contain only homogeneous

[1 2 3 5 8 2]


In [8]:
a = [1,2,3,5,8,2.0]
b = np.array(a*3)
print(b) 

[1. 2. 3. 5. 8. 2. 1. 2. 3. 5. 8. 2. 1. 2. 3. 5. 8. 2.]


In [12]:
b = np.ones(10,dtype=int)
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [13]:
b = np.ones((2,3),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [14]:
b = np.zeros(10,dtype=int)
print(b)

[0 0 0 0 0 0 0 0 0 0]


In [15]:
b = np.zeros((2,3),dtype=int)
print(b)

[[0 0 0]
 [0 0 0]]


In [16]:
b = np.full(3,5)
print(b)

[5 5 5]


In [17]:
b = np.full(3,5,dtype=float)
print(b)

[5. 5. 5.]


In [18]:
b = np.empty(4)
print(b)

[0.00000000e+000 1.32875841e-311 1.32875841e-311 1.32875841e-311]


In [19]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
a = np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [23]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
b = np.linspace(2,10)
b
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


In [34]:
b = np.linspace(2,10,5,dtype=int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [38]:
b = np.identity(3)
b
# only get square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
b = np.random.rand(3)
b

array([0.75819721, 0.21505483, 0.50815776])

In [43]:
b = np.random.rand(10)*10
b

array([5.15770223, 7.70371821, 8.28783867, 9.05160967, 0.14892735,
       3.93316603, 5.71887158, 9.18720716, 7.49210041, 0.69313483])

In [44]:
b = np.random.rand(2,3)
b

array([[0.59413319, 0.73784837, 0.39292833],
       [0.81814624, 0.18726429, 0.33402215]])

In [58]:
b = np.random.randint(0,4)
b

2

In [60]:
b = np.linspace(9,49)
b

array([ 9.        ,  9.81632653, 10.63265306, 11.44897959, 12.26530612,
       13.08163265, 13.89795918, 14.71428571, 15.53061224, 16.34693878,
       17.16326531, 17.97959184, 18.79591837, 19.6122449 , 20.42857143,
       21.24489796, 22.06122449, 22.87755102, 23.69387755, 24.51020408,
       25.32653061, 26.14285714, 26.95918367, 27.7755102 , 28.59183673,
       29.40816327, 30.2244898 , 31.04081633, 31.85714286, 32.67346939,
       33.48979592, 34.30612245, 35.12244898, 35.93877551, 36.75510204,
       37.57142857, 38.3877551 , 39.20408163, 40.02040816, 40.83673469,
       41.65306122, 42.46938776, 43.28571429, 44.10204082, 44.91836735,
       45.73469388, 46.55102041, 47.36734694, 48.18367347, 49.        ])

In [61]:
b = np.eye(5,6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])