In [2]:
import numpy as np

In [3]:
arr = np.random.randint(10,60,(5,3,3))

In [4]:
arr

array([[[43, 50, 17],
        [44, 26, 46],
        [39, 27, 31]],

       [[34, 58, 44],
        [23, 41, 13],
        [14, 58, 15]],

       [[36, 38, 30],
        [53, 22, 16],
        [13, 56, 35]],

       [[53, 20, 27],
        [22, 42, 13],
        [30, 56, 59]],

       [[32, 18, 27],
        [42, 44, 38],
        [22, 22, 26]]])

In [5]:
arr[0]

array([[43, 50, 17],
       [44, 26, 46],
       [39, 27, 31]])

In [6]:
arr[0:1]

array([[[43, 50, 17],
        [44, 26, 46],
        [39, 27, 31]]])

In [7]:
arr.ndim

3

In [8]:
arr.shape

(5, 3, 3)

In [9]:
arr[0:2,::,-1]

array([[17, 46, 31],
       [44, 13, 15]])

In [10]:
arr[0,0,0]=500

In [11]:
arr

array([[[500,  50,  17],
        [ 44,  26,  46],
        [ 39,  27,  31]],

       [[ 34,  58,  44],
        [ 23,  41,  13],
        [ 14,  58,  15]],

       [[ 36,  38,  30],
        [ 53,  22,  16],
        [ 13,  56,  35]],

       [[ 53,  20,  27],
        [ 22,  42,  13],
        [ 30,  56,  59]],

       [[ 32,  18,  27],
        [ 42,  44,  38],
        [ 22,  22,  26]]])

In [12]:
arr.max()

500

In [13]:
arr.min()

13

In [14]:
arr.mean()

43.82222222222222

In [15]:
arr = np.array([2,4,6])
arr1 = np.array([[2,4,6],[4,6,8]])
arr+arr1

array([[ 4,  8, 12],
       [ 6, 10, 14]])

In [16]:
arr*arr1

array([[ 4, 16, 36],
       [ 8, 24, 48]])

In [17]:
arr = np.random.randint(2,10,(7,3))

In [18]:
arr

array([[2, 5, 8],
       [3, 8, 9],
       [3, 4, 3],
       [7, 8, 5],
       [5, 4, 5],
       [2, 6, 6],
       [5, 2, 3]])

In [19]:
arr.T

array([[2, 3, 3, 7, 5, 2, 5],
       [5, 8, 4, 8, 4, 6, 2],
       [8, 9, 3, 5, 5, 6, 3]])

In [20]:
arr.T.shape

(3, 7)

In [22]:
arr = np.array([2,4,6])
arr1 = np.array([[2,4,6],[4,6,8]])

In [23]:
np.concatenate(arr+arr1)

array([ 4,  8, 12,  6, 10, 14])

In [25]:
# len(arr[arr>4])

In [26]:
arr = np.random.randint(1,200,100)

In [27]:
arr

array([102, 183,  84, 127,  65, 179, 184, 140,  84,  93,  92, 134, 170,
        51,  47,  99, 152,  63, 142,  70, 187,  38,  21, 179, 162,   8,
       103, 103, 147,  87,  28, 120, 112, 176, 128, 107,  25, 144,  19,
       171,   8, 170,  98,   3, 168, 151,  35,  29,   6,  17, 181, 132,
        25, 141,  53, 110,  59,  46, 115,  36,  88, 145,  91,  87,  89,
        49,   5, 134, 146,   4, 142, 190, 177,  52, 163,  38, 160,  62,
        30,  36,  65,   5,  26,  74, 163, 179, 135, 178, 111, 144, 122,
        96, 165,  49, 134, 163, 125, 164, 119, 180])

In [28]:
len(arr[arr>150])

25

In [30]:
np.unique(arr).shape

(81,)

In [31]:
len(np.unique(arr))

81

In [32]:
np.argmin(arr) #return index of minimum position

43

In [33]:
np.argmax(arr) #return index of maximum position

71

In [34]:
arr.sort()

In [35]:
arr

array([  3,   4,   5,   5,   6,   8,   8,  17,  19,  21,  25,  25,  26,
        28,  29,  30,  35,  36,  36,  38,  38,  46,  47,  49,  49,  51,
        52,  53,  59,  62,  63,  65,  65,  70,  74,  84,  84,  87,  87,
        88,  89,  91,  92,  93,  96,  98,  99, 102, 103, 103, 107, 110,
       111, 112, 115, 119, 120, 122, 125, 127, 128, 132, 134, 134, 134,
       135, 140, 141, 142, 142, 144, 144, 145, 146, 147, 151, 152, 160,
       162, 163, 163, 163, 164, 165, 168, 170, 170, 171, 176, 177, 178,
       179, 179, 179, 180, 181, 183, 184, 187, 190])

In [36]:
arr[::-1]

array([190, 187, 184, 183, 181, 180, 179, 179, 179, 178, 177, 176, 171,
       170, 170, 168, 165, 164, 163, 163, 163, 162, 160, 152, 151, 147,
       146, 145, 144, 144, 142, 142, 141, 140, 135, 134, 134, 134, 132,
       128, 127, 125, 122, 120, 119, 115, 112, 111, 110, 107, 103, 103,
       102,  99,  98,  96,  93,  92,  91,  89,  88,  87,  87,  84,  84,
        74,  70,  65,  65,  63,  62,  59,  53,  52,  51,  49,  49,  47,
        46,  38,  38,  36,  36,  35,  30,  29,  28,  26,  25,  25,  21,
        19,  17,   8,   8,   6,   5,   5,   4,   3])

In [37]:
import random

In [38]:
random.randint(5,9)

5

In [39]:
random.random()

0.7084741039863831

In [41]:
ls = [2,4,6,8,9]
random.choice(ls)

9

In [42]:
random.choices(ls,k=2)

[4, 2]

In [ ]:
# time datetime

In [43]:
import time

In [44]:
time.localtime()

time.struct_time(tm_year=2024, tm_mon=6, tm_mday=16, tm_hour=0, tm_min=16, tm_sec=3, tm_wday=6, tm_yday=168, tm_isdst=0)