In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50,60,70])

In [3]:
arr

array([10, 20, 30, 40, 50, 60, 70])

In [4]:
arr[0:5]

array([10, 20, 30, 40, 50])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(7,)

In [7]:
arr = np.array([10,20,30,40,50,60,70,'aditya'])

In [8]:
arr

array(['10', '20', '30', '40', '50', '60', '70', 'aditya'], dtype='<U11')

In [9]:
arr[0:6]

array(['10', '20', '30', '40', '50', '60'], dtype='<U11')

In [10]:
arr.ndim

1

In [11]:
arr.shape

(8,)

In [12]:
arr = [[1,2,3],[4,5,6]]
arr2 = np.array(arr)

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.ndim

2

In [17]:
arr = [[[1,2,3],[4,5,6],[7,8,9]]]
arr2 = np.array(arr)

In [18]:
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
arr2.shape

(1, 3, 3)

In [21]:
arr2.ndim

3