In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50,60])

In [4]:
arr

array([10, 20, 30, 40, 50, 60])

In [5]:
arr[-2]

50

In [6]:
arr[0:5]

array([10, 20, 30, 40, 50])

In [7]:
arr.shape

(6,)

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [14]:
np.linspace(5,10)

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [15]:
np.random.randint((5,2))

array([4, 0])

In [16]:
np.random.random(10)

array([0.28097462, 0.46747166, 0.88179997, 0.53978008, 0.6392524 ,
       0.10316459, 0.09838587, 0.38462795, 0.31614693, 0.30224101])

In [17]:
np.arange(24).reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
arr = np.arange(26).reshape(2,13)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [19]:
arr = np.arange(26).reshape(13,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25]])

In [20]:
b = arr.ravel() #ravel is used to flatten array
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [21]:
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25]])

In [22]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [23]:
arr.shape

(13, 2)

In [24]:
arr = np.array([10,20,30,40,50,60])

In [25]:
arr[1]

20

In [26]:
arr[:]

array([10, 20, 30, 40, 50, 60])

In [27]:
arr.shape

(6,)

In [28]:
arr = np.arange(60).reshape(12,5)

In [29]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [30]:
arr[0]

array([0, 1, 2, 3, 4])

In [31]:
arr[-1]

array([55, 56, 57, 58, 59])

In [32]:
arr[0:3,3:5]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [39]:
arr[0:12,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25],
       [34, 33, 32, 31, 30],
       [39, 38, 37, 36, 35],
       [44, 43, 42, 41, 40],
       [49, 48, 47, 46, 45],
       [54, 53, 52, 51, 50],
       [59, 58, 57, 56, 55]])

In [40]:
arr = np.random.randint(10,50,(5,3,3))

In [41]:
arr.shape

(5, 3, 3)

In [42]:
arr

array([[[11, 17, 31],
        [37, 43, 23],
        [43, 40, 17]],

       [[46, 47, 42],
        [38, 30, 28],
        [11, 13, 12]],

       [[18, 22, 46],
        [34, 49, 11],
        [40, 17, 49]],

       [[13, 21, 15],
        [38, 45, 43],
        [11, 25, 32]],

       [[43, 47, 23],
        [35, 34, 11],
        [40, 37, 34]]])

In [43]:
arr.ndim

3